# Master Pods Repo
source 'https://github.com/CocoaPods/Specs.git'

# Private Pods Repo
source 'git@bitbucket.org:thedistance/thedistancekit-cocoapods.git'

# pod configuration
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

# define 
workspace '../MozQuito'
xcodeproj '../MozQuito'

target 'MozQuito' do

xcodeproj '../MozQuito'

### CORE PODS ###

pod 'TheDistanceCore', :path => 'TheDistanceCore'
pod 'ViperKit', :path => 'ViperKit'
pod 'MagicalRecord'

### DISTRIBUTION PODS ###

pod 'GoogleAnalytics'
pod 'Fabric'
pod 'Crashlytics'

### NETWORKING PODS ###

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'PSOperations', :git => 'https://github.com/joshc89/PSOperations.git'

pod 'hpple'

### UI PODS ###

pod 'M13ProgressSuite'
pod 'StackView', :path => 'StackView'

### Josh's Development Pods ###

pod 'SwiftInPractice', :path => 'SwiftInPractice'
pod 'AdvancedOperationKit', :path => 'AdvancedOperationKit'

end

target 'MozQuitoTests' do

xcodeproj '../MozQuito'

pod 'AdvancedOperationKit', :path => 'AdvancedOperationKit'
pod 'ViperKit', :path => 'ViperKit'

end


